In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df=sns.load_dataset("tips")

In [3]:
from sklearn.preprocessing  import LabelEncoder
encoder_time=LabelEncoder()
encoder_day=LabelEncoder()
encoder_data=encoder_time.fit_transform(df["time"])
encoder_data=encoder_day.fit_transform(df["day"])

In [4]:
print("classes",encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [5]:
encoder_data

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [6]:
for category , number in zip(encoder_time.classes_,range(len(encoder_time.classes_))):
  print(category,"------",number)

Dinner ------ 0
Lunch ------ 1

In [7]:
print("classes",encoder_day.classes_)

classes ['Fri' 'Sat' 'Sun' 'Thur']

In [8]:
for category , number in zip(encoder_day.classes_,range(len(encoder_day.classes_))):
  print(category,"------",number)

Fri ------ 0
Sat ------ 1
Sun ------ 2
Thur ------ 3

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [15]:
ohe=OneHotEncoder(sparse_output=False,drop="first")
ohe_encoder=ohe.fit_transform(df[["sex","smoker"]])

In [16]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [17]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [18]:
from sklearn.preprocessing import FunctionTransformer

In [19]:
log=FunctionTransformer(np.log10)
log.fit_transform(df["tip"])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [21]:
log_2=FunctionTransformer(np.log2)
log_2.fit_transform(df["tip"])

0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

In [23]:
from sklearn.preprocessing import PowerTransformer

In [26]:
x=np.array([[-1],[0],[3],[5],[10],[50]])

In [27]:
x

array([[-1],
       [ 0],
       [ 3],
       [ 5],
       [10],
       [50]])

In [28]:
pt=PowerTransformer(method="yeo-johnson")

In [32]:
x_transformed=pt.fit_transform(x)
print("Original:")
print(x.ravel())
print("\nTranformed:")
print(np.round(x_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

Original:
[-1  0  3  5 10 50]

Tranformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [34]:
y=np.array([[-1],[0],[3],[5],[10],[50]])
y

array([[-1],
       [ 0],
       [ 3],
       [ 5],
       [10],
       [50]])

In [35]:
y_transformed=pt.fit_transform(y)
print("Original:")
print(x.ravel())
print("\nTranformed:")
print(np.round(y_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

Original:
[-1  0  3  5 10 50]

Tranformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [40]:
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Department': ['Engineering', 'Data Science', 'HR', 'Engineering', np.nan, 'Finance', 'Data Science', np.nan],
    'City': ['New York', 'London', np.nan, 'Paris', 'New York', 'London', 'Paris', 'London'],
    'Education': ["Bachelor's", "Master's", np.nan, "Ph.D.", "Bachelor's", np.nan, "Master's", "Bachelor's"],
    'Age': [28, 34, np.nan, 42, 25, 39, np.nan, 30],
    'Salary': [65000, 85000, 50000, np.nan, 55000, 92000, np.nan, 70000],
    'Experience_Years': [2.5, 6.0, 1.0, np.nan, 1.5, 8.0, np.nan, 4.2]
}

In [41]:
df = pd.DataFrame(data)

In [42]:
df.head()

,Employee_ID,Department,City,Education,Age,Salary,Experience_Years
0,101,Engineering,New York,Bachelor's,28.0,65000.0,2.5
1,102,Data Science,London,Master's,34.0,85000.0,6.0
2,103,HR,NaN,NaN,NaN,50000.0,1.0
3,104,Engineering,Paris,Ph.D.,42.0,NaN,NaN
4,105,NaN,New York,Bachelor's,25.0,55000.0,1.5

In [45]:
from sklearn.impute import  SimpleImputer

In [47]:
imputer=SimpleImputer(strategy="mean")
imputer.fit_transform(df[["Salary"]])

array([[65000.],
       [85000.],
       [50000.],
       [69500.],
       [55000.],
       [92000.],
       [69500.],
       [70000.]])

In [56]:
imputer=SimpleImputer(strategy="mean")
df["new_salary"]=imputer.fit_transform(df[["Salary"]]).flatten()
df

,Employee_ID,Department,City,Education,Age,Salary,Experience_Years,new_salary
0,101,Engineering,New York,Bachelor's,28.0,65000.0,2.5,65000.0
1,102,Data Science,London,Master's,34.0,85000.0,6.0,85000.0
2,103,HR,NaN,NaN,NaN,50000.0,1.0,50000.0
3,104,Engineering,Paris,Ph.D.,42.0,NaN,NaN,69500.0
4,105,NaN,New York,Bachelor's,25.0,55000.0,1.5,55000.0
5,106,Finance,London,NaN,39.0,92000.0,8.0,92000.0
6,107,Data Science,Paris,Master's,NaN,NaN,NaN,69500.0
7,108,NaN,London,Bachelor's,30.0,70000.0,4.2,70000.0

In [61]:
imputer=SimpleImputer(strategy="median")
df["new_Experience_Years"]=imputer.fit_transform(df[["Experience_Years"]]).flatten()
df

,Employee_ID,Department,City,Education,Age,Salary,Experience_Years,new_salary,new_Experience_year,new_Experience_Years
0,101,Engineering,New York,Bachelor's,28.0,65000.0,2.5,65000.0,65000.0,2.50
1,102,Data Science,London,Master's,34.0,85000.0,6.0,85000.0,85000.0,6.00
2,103,HR,NaN,NaN,NaN,50000.0,1.0,50000.0,50000.0,1.00
3,104,Engineering,Paris,Ph.D.,42.0,NaN,NaN,67500.0,67500.0,3.35
4,105,NaN,New York,Bachelor's,25.0,55000.0,1.5,55000.0,55000.0,1.50
5,106,Finance,London,NaN,39.0,92000.0,8.0,92000.0,92000.0,8.00
6,107,Data Science,Paris,Master's,NaN,NaN,NaN,67500.0,67500.0,3.35
7,108,NaN,London,Bachelor's,30.0,70000.0,4.2,70000.0,70000.0,4.20

In [64]:
imputer=SimpleImputer(strategy="most_frequent" ,)
df["City"]=imputer.fit_transform(df[["City"]]).flatten()
df

,Employee_ID,Department,City,Education,Age,Salary,Experience_Years,new_salary,new_Experience_year,new_Experience_Years,new_city
0,101,Engineering,New York,Bachelor's,28.0,65000.0,2.5,65000.0,65000.0,2.50,New York
1,102,Data Science,London,Master's,34.0,85000.0,6.0,85000.0,85000.0,6.00,London
2,103,HR,London,NaN,NaN,50000.0,1.0,50000.0,50000.0,1.00,London
3,104,Engineering,Paris,Ph.D.,42.0,NaN,NaN,67500.0,67500.0,3.35,Paris
4,105,NaN,New York,Bachelor's,25.0,55000.0,1.5,55000.0,55000.0,1.50,New York
5,106,Finance,London,NaN,39.0,92000.0,8.0,92000.0,92000.0,8.00,London
6,107,Data Science,Paris,Master's,NaN,NaN,NaN,67500.0,67500.0,3.35,Paris
7,108,NaN,London,Bachelor's,30.0,70000.0,4.2,70000.0,70000.0,4.20,London